### ISSUE TITLE
Works abnormally on flyme10

### ISSUE THREAD

**Issue by EX3124** [LSPosed/DisableFlagSecure#13]
English(Google Translate)
In flyme10, com.flyme.systemuiex is used to take screenshots, and the code for detecting window status is also included.
Search the keyword containsSecureLayers in com.flyme.systemuiex to find the code shown in the picture, delete the selected part in the picture, and then cooperate with the module to take a normal screenshot
so use
XposedHelpers.findAndHookMethod("android.view.SurfaceControl$ScreenshotHardwareBuffer", lpparam.classLoader, "containsSecureLayers", XC_MethodReplacement.returnConstant(false));
And add com.flyme.systemuiex to the scope to take a normal screenshot

中文
在flyme10中,使用了com.flyme.systemuiex来进行截图,检测窗口状态的代码也在其中.
在com.flyme.systemuiex中搜索关键字containsSecureLayers即可找到如图所示的代码,将图中选中的部分删掉,再配合模块就能正常截图了
所以使用
XposedHelpers.findAndHookMethod("android.view.SurfaceControl$ScreenshotHardwareBuffer", lpparam.classLoader, "containsSecureLayers", XC_MethodReplacement.returnConstant(false));
并在作用域中加上com.flyme.systemuiex即可正常截图

![S30731-00005207_bin mt plus](https://github.com/LSPosed/DisableFlagSecure/assets/70867298/2b35f34b-f183-4da4-bf98-6f0f3820e90d)

**Comment by yujincheng08** [comment]
欢迎 PR
