### ISSUE TITLE
Doesn't work...

### ISSUE THREAD

**Issue by Mikoros** [LSPosed/DisableFlagSecure#15]
Doesn't work on OP 9 Pro LE2123, Android 12 in Netflix app...
I have Magisk 26.1 installed with Zygisk - LsPosed 1.8.6

**Comment by yujincheng08** [comment]
netflix uses drm

**Comment by Mikoros** [comment]
So should I use something like liboecryptodisabler ?

**Comment by Mikoros** [comment]
That's doesn't make sense because I still can play the video without liboecryptodisabler, I just can't take screenshots

**Comment by yujincheng08** [comment]
u cannot screenshot drm content. it's protected by hardware. u cannot crack it at the software level.
