### ISSUE TITLE
Not Working on Android 14

### ISSUE THREAD

**Issue by tryigit** [LSPosed/DisableFlagSecure#17]
![Screenshot_2023-08-19-03-40-51-000_com android chrome](https://github.com/LSPosed/DisableFlagSecure/assets/40565628/599a52f8-9cd5-49cc-8538-e45a62457f27)

No need to explain much, patch for android 14 should be arranged

**Comment by navaneeth-dev** [comment]
Doesn't work on Android 13, says screenshot isn't available

**Comment by Ra2feto** [comment]
> It seems caused by 0x04 flag has been set to SurfaceFlinger for currLayer, which may caused this situation.
> 
> I solved the problem on my side and with a module. Only information.

can you please tell us the steps to fix as it isn't working on pixel 4xl running android 13
