### ISSUE TITLE
ColorOS12（Android 12）无效，附日志

### ISSUE THREAD

**Issue by Marukon** [LSPosed/DisableFlagSecure#2]
我的LSP版本：
![photo_2022-02-22_19-04-50](https://user-images.githubusercontent.com/6285343/155119908-e259a026-10f7-4429-8ab7-b683bffa341e.jpg)
激活模块并重启后，有Flag_secure的app仍然不能截图
以下是日志，麻烦作者帮忙看看，谢谢。

[LSPosed_2022-02-22T18_52_11.027.zip](https://github.com/LSPosed/DisableFlagSecure/files/8116052/LSPosed_2022-02-22T18_52_11.027.zip)
[LSPosed_2022-02-22T18_52_14.195.zip](https://github.com/LSPosed/DisableFlagSecure/files/8116053/LSPosed_2022-02-22T18_52_14.195.zip)
[logcat.zip](https://github.com/LSPosed/DisableFlagSecure/files/8116054/logcat.zip)

**Comment by tehcneko** [comment]
不支持 Android 12
