### ISSUE TITLE
Android 13 Samsung A04 (non-rooted) doesn't support it!

### ISSUE THREAD

**Issue by hamadzidani** [LSPosed/DisableFlagSecure#20]
After installing the apk, my phone still throwing "Can't take screenshots due to security policy"

**Comment by hamadzidani** [comment]
@JasonKhew96 explain, for god sake!

**Comment by JasonKhew96** [comment]
> @JasonKhew96 explain, for god sake!

root only

**Comment by hamadzidani** [comment]
is there a workaround for non-rooted devices?
