### ISSUE TITLE
Error with this module in LSposed

### ISSUE THREAD

**Issue by foxi69** [LSPosed/DisableFlagSecure#25]
[LSPosed_2023-12-11T01_08_04.802821.zip](https://github.com/LSPosed/DisableFlagSecure/files/13629702/LSPosed_2023-12-11T01_08_04.802821.zip)

Can you help me with this error?
Device: Redmi Note 9 Pro
LSPosed 1.9.2
Magisk 26.4
LinageOS 20

DisableFlagSecure 3.0.0. even error with 2.2.0

**Comment by JasonKhew96** [comment]
ignore this error if it's working
