### ISSUE TITLE
Not working on Android 11.1.2.2

### ISSUE THREAD

**Issue by molitar** [LSPosed/DisableFlagSecure#27]
So I have Magisk with LSPosed installed.  I have the LSPosed module enabled and download this disableflagsecure and than in LSPosed I enabled it than selected BitWarden and Microsoft Swiftkey but it is not working when I try to take a screenshot of Bitwarden it reports it is blocked. 

Am I configuring something wrong?

LSPosed DisableFlagSecure > System framework checked ; Bitwarden checked ; Microsoft Swift Key checked

**Comment by Howard20181** [comment]
There is no need to select apps other than the system framework

**Comment by molitar** [comment]
OK so basically does not work with Android 11 your saying because this does not work at all. Be nice for that to be in the description
