### ISSUE TITLE
Not working on OnePlus devices (8T/9Pro) Android 13.1

### ISSUE THREAD

**Issue by Astronxd** [LSPosed/DisableFlagSecure#28]
Tested on OnePlus 8T and 9 pro, screenshot restrictions still persosts after installing this module.

**Comment by psycho91** [comment]
> Tested on OnePlus 8T and 9 pro, screenshot restrictions still persosts after installing this module.

Hey, same device and version, I've tried with telegram (flagged the app in the Ls manager) but unfortunately doesn't work.. let's see :(

**Comment by psycho91** [comment]
> Tested on OnePlus 8T and 9 pro, screenshot restrictions still persosts after installing this module.

Instead of a screenshot, try with record screen. For me works on telegram

**Comment by Astronxd** [comment]
[LSPosed_2024-01-16T09_20_53.152667.zip](https://github.com/LSPosed/DisableFlagSecure/files/13945074/LSPosed_2024-01-16T09_20_53.152667.zip)

Here is the Log. I think this module isn't working on OxygenOS. There is this module that's working if it helps.
https://github.com/VarunS2002/Xposed-Disable-FLAG_SECURE

**Comment by aviraxp** [comment]
OxygenOS has another apk handling screenshot and needs additional hook.

**Comment by aviraxp** [comment]
https://github.com/Nyrest/LuckyTool/blob/main/app%2Fsrc%2Fmain%2Fjava%2Fcom%2Fluckyzyx%2Fluckytool%2Fhook%2Fapps%2Fscreenshot%2FRemoveScreenshotPrivacyLimit.kt

**Comment by Astronxd** [comment]
> > [LSPosed_2024-01-16T09_20_53.152667.zip](https://github.com/LSPosed/DisableFlagSecure/files/13945074/LSPosed_2024-01-16T09_20_53.152667.zip)
> > Here is the Log. I think this module isn't working on any OxygenOS. To reproduce, install this module on any OxygenOS. There is this module that's working if it helps. https://github.com/VarunS2002/Xposed-Disable-FLAG_SECURE
> 
> 
[framework.zip](https://github.com/LSPosed/DisableFlagSecure/files/13945391/framework.zip)


> > [LSPosed_2024-01-16T09_20_53.152667.zip](https://github.com/LSPosed/DisableFlagSecure/files/13945074/LSPosed_2024-01-16T09_20_53.152667.zip)
> > Here is the Log. I think this module isn't working on any OxygenOS. To reproduce, install this module on any OxygenOS. There is this module that's working if it helps. https://github.com/VarunS2002/Xposed-Disable-FLAG_SECURE
> 
> upload your `/system/framework/framework.jar `here

[framework.zip](https://github.com/LSPosed/DisableFlagSecure/files/13945396/framework.zip)

Attached

**Comment by Astronxd** [comment]
![Screenshot_2024-01-16-11-40-20-12_b783bf344239542886fee7b48fa4b892](https://github.com/LSPosed/DisableFlagSecure/assets/32937797/0d5f9c09-d624-4f5d-b19c-191dabbb1092)

**Comment by yujincheng08** [comment]
dont hook apps not in recommended scope

**Comment by Astronxd** [comment]
Works on firefox private mode but not working on Netflix

**Comment by Astronxd** [comment]
Screen recording and screenshot on Netflix isn't working

**Comment by DineshValor** [comment]
Did someone found the solution on OnePlus devices??

**Comment by yujincheng08** [comment]
its fixed

**Comment by Astronxd** [comment]
https://github.com/VarunS2002/Xposed-Disable-FLAG_SECURE

This one works.

**Comment by yujincheng08** [comment]
you should read its readme carefully:

> When playing DRM encrypted content, most devices will use hardware decryption capabilities. This hardware decryption will push the video directly onto the screen, bypassing any screenshots/screenshare/recording functionality.

> One possible solution is to disable this hardware decryption by installing the Magisk module liboemcrypto.so disabler. This will force the device to not use hardware decryption and in combination with this module will enable screenshots, screen sharing and recording.

> Installing this module might have unintended consequences, such as lowered video quality.

>

**Comment by Astronxd** [comment]
https://github.com/VarunS2002/Xposed-Disable-FLAG_SECURE

This one works.

![Screenshot_2024-01-16-15-41-30-64_1416f938ee57ce661c832da32616b710](https://github.com/LSPosed/DisableFlagSecure/assets/32937797/032a86a8-1f13-47ba-ac70-2f10dc7de74f)

**Comment by yujincheng08** [comment]
its not bypassing drm, but disabling. if u disable drm, it will lower the resolution.

**Comment by Astronxd** [comment]
Is it possible to choose between these versions? On my small screen phone, I dont care about the quality tbh.

**Comment by Ylarod** [comment]
@Astronxd use camera to take pics of your phone
