### ISSUE TITLE
app exit immediately

### ISSUE THREAD

**Issue by chinasoul** [LSPosed/DisableFlagSecure#30]
### LSPosed version

1.9.2

### Android version

13

### Custom OS version

13

### Version requirement

- [X] I am using latest debug CI version

### Logs

2 apps crash: schwab and hsbc
after exit of the app, the toast syas: "DFS: incorrect module usage, remove this app from scope."

### Framework JAR

...

**Comment by yujincheng08** [comment]
incorrect module usage, remove this app from scope

**Comment by chinasoul** [comment]
I see. below steps is a must:
1. do not select any app, leaving the default one selected i.e. system framework
2. reboot
