### ISSUE TITLE
DFS: Incorrect module usage, remove this app from scope.

### ISSUE THREAD

**Issue by SavageTheUnicorn** [LSPosed/DisableFlagSecure#36]
### LSPosed version

LSPatch 0.6

### Android version

14

### Custom OS version

N/A

### Version requirement

- [X] I am using latest debug CI version

### Logs

N/A.
Module is embedded into target application using LSPatch+Shizuku and causes this error with 3.1.0. Using 3.0.0 this error does not show, but it also does not successfully disable secure flags. Upon first launch using 3.0.0 the target application loads a video immediately and caused it to display "Could not load video." a few times before going to a black screen. Relaunching the application allows it to function like normal but flags are still disabled. 

### Framework JAR

N/A

**Comment by Joackk** [comment]
I have the same problem

**Comment by AntarCrypto** [comment]
How did you patch the apk with this module in my case it's not even appearing in lspatch

**Comment by luckyabsoluter** [comment]
It does work with LSPatch:

https://apt.izzysoft.de/fdroid/index/apk/com.varuns2002.disable_flag_secure

https://github.com/VarunS2002/Xposed-Disable-FLAG_SECURE
