### ISSUE TITLE
Please add Samsung One UI 6.1 support

### ISSUE THREAD

**Issue by Pharaoh2k** [LSPosed/DisableFlagSecure#43]
### LSPosed version

7058

### Android version

14

### Custom OS version

One ui 6.1

### Version requirement

- [X] I am using latest debug CI version

### Logs

[LSPosed_2024-05-28T15_45_45.703940.zip](https://github.com/LSPosed/DisableFlagSecure/files/15466587/LSPosed_2024-05-28T15_45_45.703940.zip)

### Framework JAR

[Samsung OUI 6.1 JARS.zip](https://github.com/LSPosed/DisableFlagSecure/files/15466428/Samsung.OUI.6.1.JARS.zip)
[Samsung OUI 6.1 JARS.z01.ZIP](https://github.com/LSPosed/DisableFlagSecure/files/15466435/Samsung.OUI.6.1.JARS.z01.ZIP)

Please remove the ZIP extension from the z01 file to be able to extract the 2 files.

**Comment by Pharaoh2k** [comment]
Thesis.
Can't install these and can't even install the new 3.2.2 release you posted an hour ago, installer gets stuck on initalizing. 
Please fix.

**Comment by aviraxp** [comment]
@Pharaoh2k 就这个

**Comment by Pharaoh2k** [comment]
Sorry, issue on my phone. It works now. Thanks. 🙏
