### ISSUE TITLE
 Android 13 does not work properly

### ISSUE THREAD

**Issue by 865258951** [LSPosed/DisableFlagSecure#5]
Today, after I updated Android 13, apps that are not allowed to screenshot after the module is enabled cannot screenshot.

**Comment by slanterns** [comment]
Reproduced after upgrading to Android 13 (MIUI 14).

**Comment by lxxself** [comment]
@yujincheng08 
Why does deoptimizeMethod some methods make it compatible with Android 13? Can you please explain?
想请教一下：为什么去优化一些方法就可以支持 Android 13 了？
