### ISSUE TITLE
When attempting to screen record some video streaming apps (e.g., Bongo, Hoichoi), the phone crashes and reboots.

### ISSUE THREAD

**Issue by tareq71ahmed** [LSPosed/DisableFlagSecure#51]
### LSPosed version

https://github.com/LSPosed/LSPosed/releases/tag/v1.9.2

### Android version

13

### Custom OS version

stock (Realme 8 5G) RMX3241

### Version requirement

- [X] I am using latest debug CI version

### Behavior

When I first enter a streaming app and take a screenshot of a movie, then take a screenshot of another movie in the same app, the second screenshot ends up being the same as the first one. 

The second major issue is that sometimes I can screen record certain movies, but other times, when I try to screen record a different movie, my phone automatically reboots.

### Logs

[Uploading LSPosed_2024-06-15T02_40_52.807329.zip…]()

### Framework, Services, and Screenshot App

![Screenshot_2024-06-15-02-31-59-39_b783bf344239542886fee7b48fa4b892](https://github.com/LSPosed/DisableFlagSecure/assets/30871151/441afc53-3882-4a0f-a4f9-daaf22e48337)

**Comment by yujincheng08** [comment]
invalid log
