### ISSUE TITLE
HyperOS A13无法使用

### ISSUE THREAD

**Issue by lns103** [LSPosed/DisableFlagSecure#52]
### LSPosed version

7024

### Android version

13

### Custom OS version

HyperOS 1.0.2.0

### Version requirement

- [X] I am using latest debug CI version

### Behavior

Toast提示该页面不允许截图。
使用哔哩哔哩播放DRM视频的截图为纯黑色（未启用模块时，仅视频区域为黑色）
使用哔哩哔哩播放DRM视频时的后台卡片为纯透明
![IMG_20240617_163612](https://github.com/LSPosed/DisableFlagSecure/assets/49310852/b354a8af-b68e-42d1-817f-7135173d7db5)
![IMG_20240617_163639](https://github.com/LSPosed/DisableFlagSecure/assets/49310852/f19bdf14-2ac5-4480-a9a7-2788f0583a10)

### Logs

[LSPosed_2024-06-17T16_33_04.281502.zip](https://github.com/user-attachments/files/15864126/LSPosed_2024-06-17T16_33_04.281502.zip)

### Framework, Services, and Screenshot App

https://files.catbox.moe/9nvxhd.zip

**Comment by yujincheng08** [comment]
DRM 无法破解

**Comment by lns103** [comment]
> DRM 无法破解

 禁用安全标志检测器 无法截图，弹toast提示，DRM只是希望能修复后台卡片异常，没指望能截图

**Comment by lns103** [comment]
![20240617_180025](https://github.com/LSPosed/DisableFlagSecure/assets/49310852/0d4060d5-f479-4736-b7b4-aa981fa50aaa)
这个界面无法截图，能修吗？

**Comment by yujincheng08** [comment]
![image](https://github.com/LSPosed/DisableFlagSecure/assets/5022927/4b169217-5e18-4850-89b9-662c9c69ec1f)
我也不知道为什么

**Comment by lns103** [comment]
> https://github.com/LSPosed/DisableFlagSecure/actions/runs/9546445078

DRM的问题正常了，但是flag secure的界面还是无法截图（后台卡片可以显示）
