### ISSUE TITLE
Two modules with nearly same name & versioning!?

### ISSUE THREAD

**Issue by Enkidu70** [LSPosed/DisableFlagSecure#6]
Meanwhile there are two looking very similar modules:

* https://github.com/LSPosed/DisableFlagSecure

&

* https://github.com/VarunS2002/Xposed-Disable-FLAG_SECURE

Are those identical?

If not, could you please add some info what's the difference?

Tnx in advance.

**Comment by yujincheng08** [comment]
ours only hooks system framewor.
