### ISSUE TITLE
"My HEB" app crashes on launch

### ISSUE THREAD

**Issue by altermere** [LSPosed/DisableFlagSecure#61]
### LSPosed version

7024

### Android version

13

### Custom OS version

no

### Version requirement

- [X] I am using latest debug CI version

### Behavior

As soon as I try to launch My HEB app it immediately crashes. It works normally if I don't select it in the DisableFlag module. 
Phone: moto edge 2023 plus

### Logs

[LSPosed_2024-08-20T22_48_33.886267.zip](https://github.com/user-attachments/files/16685776/LSPosed_2024-08-20T22_48_33.886267.zip)

### Framework, Services, and Screenshot App

https://files.catbox.moe/7g1v2c.zip

**Comment by JasonKhew96** [comment]
https://github.com/LSPosed/DisableFlagSecure/blob/main/README.md#usage
