### ISSUE TITLE
Screencast not working

### ISSUE THREAD

**Issue by Jackamma** [LSPosed/DisableFlagSecure#64]
### LSPosed version

1.9.2 (7024)

### Android version

14

### Custom OS version

RMX3301_14.0.0.810(EX01)

### Version requirement

- [X] I am using latest debug CI version

### Behavior

Screenshot are working fine but with this module enabled, I cannot use Screencast app on my realme gt2 pro. I just enabled the module on the suggested apps and nothing else. If I disable the module from LSPosed, the screencast app works again.

Module version: 4.1.0

### Logs

Tell me if it's needed

### Framework, Services, and Screenshot App

Tell me if it's needed

**Comment by vvb2060** [comment]
no log

**Comment by Jackamma** [comment]
> no log

Hi, how can I provide logs? Should they be screencast app's log? If I can help you with this one, I'll provide them. Otherwise don't worry and thank you for your work.
