### ISSUE TITLE
Support for com.google.android.gms

### ISSUE THREAD

**Issue by dhyanKaro** [LSPosed/DisableFlagSecure#74]
### LSPosed version

1.9.2

### Android version

14

### Custom OS version

14

### Version requirement

- [X] I am using latest debug CI version

### Behavior

Any chance this app can support com.google.android.gms (Google Play Services)? That screen that pops up when you do Settings > Google > Manage my account

### Logs

👨🏻‍🚀👨🏻‍🚀👨🏻‍🚀

### Framework, Services, and Screenshot App

👨🏻‍🚀👨🏻‍🚀👨🏻‍🚀

**Comment by znbaboy** [comment]
@dhyanKaro https://github.com/LSPosed/DisableFlagSecure/releases/tag/v3.1.0 works
