### ISSUE TITLE
Telegram doesn't allow to take screenshot | Android 13\

### ISSUE THREAD

**Issue by psycho91** [LSPosed/DisableFlagSecure#8]
Hi Dear,

I'm currently on A13, latest LSposed, installed DisabledFlagSecure, selected the apps that I need but telegram doesn't allow me to take screenshot.

Could you please give me support?

**Comment by yujincheng08** [comment]
you shouldn't select any apps.

**Comment by psycho91** [comment]
> you shouldn't select any apps.

unfortunately doesn't change

**Comment by CyberstormFox** [comment]
The problem persists for me too, and is not selected in Lsposed. This is not a a resolution of the problem deecribed.
